language: android
notifications:
  email: false

android: 
  components: 
       - platform-tools
       - tools
       - build-tools-25.0.0 
       - android-25 
       - extra-android-m2repository 
       - extra-android-support 
       
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'

before_install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"
       
install:
  - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  - unzip -qq android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r16b
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - env
  
before_script:
- git clone https://github.com/switch-iot/n2n_vLTS.git --recurse-submodules
- cd n2n_vLTS/An2n
- chmod +x gradlew
 
script:
- './gradlew assemble'
- 'tar -czvf hin2n.tar.gz *'
- 'curl -T hin2n.tar.gz -u yzcmjsn@gmail.com:0339109523 https://dav.box.com/dav/'
